"""Expanded Item model

Revision ID: 0517339a4132
Revises: df1b3954526c
Create Date: 2025-07-12 16:13:44.491827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0517339a4132'
down_revision: Union[str, Sequence[str], None] = 'df1b3954526c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('items', sa.Column('brand', sa.String(), nullable=True))
    op.add_column('items', sa.Column('color', sa.String(), nullable=True))
    op.add_column('items', sa.Column('material', sa.String(), nullable=True))
    op.add_column('items', sa.Column('location', sa.String(), nullable=True))
    op.add_column('items', sa.Column('exchange_method', sa.String(), nullable=True))
    op.add_column('items', sa.Column('views', sa.Integer(), nullable=True))
    op.alter_column('items', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('items', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('items', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('items', 'views')
    op.drop_column('items', 'exchange_method')
    op.drop_column('items', 'location')
    op.drop_column('items', 'material')
    op.drop_column('items', 'color')
    op.drop_column('items', 'brand')
    op.drop_column('items', 'created_at')
    # ### end Alembic commands ###
