"""Add approved field to Item

Revision ID: 189bdf0511f4
Revises: 8a22cd8a8c8c
Create Date: 2025-07-12 14:49:42.384188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '189bdf0511f4'
down_revision: Union[str, Sequence[str], None] = '8a22cd8a8c8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('approved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'approved')
    # ### end Alembic commands ###
