"""Expanded Item model

Revision ID: 3a91c2dbf902
Revises: 0517339a4132
Create Date: 2025-07-12 16:16:51.597096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a91c2dbf902'
down_revision: Union[str, Sequence[str], None] = '0517339a4132'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'exchange_method')
    op.drop_column('items', 'views')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('views', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('exchange_method', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
