"""Expanded Item model

Revision ID: d349b364bd55
Revises: 3a91c2dbf902
Create Date: 2025-07-12 16:22:16.577210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd349b364bd55'
down_revision: Union[str, Sequence[str], None] = '3a91c2dbf902'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('exchange_method', sa.String(), nullable=True))
    op.add_column('items', sa.Column('views', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'views')
    op.drop_column('items', 'exchange_method')
    # ### end Alembic commands ###
